### ISSUE TITLE
カラーの命名について

### ISSUE THREAD

**Issue by show-coco** [show-coco/cloud-town#13]
[議論の出発点](https://github.com/show-coco/cloud-event/pull/12/files#r658429112)

**Comment by show-coco** [comment]
by @kazuhe 
だいたい2色くらいあれば事足りる気がするので、下記のようにlightとdarkにしておくのどうですか？？
（main or baseの標準色があっても良いかも）

```
gray: {
  light: "#f3f3f3",
  dark: "濃い色",
}
```

**Comment by show-coco** [comment]
僕的にはFigmaでカラーコードをきちんと定義しておいて、命名はFigmaとフロントで合わせておけば、コーディングするときはFigmaから名前を簡単に見れるので特に問題にならず楽にコーディングできるかなと思いました！

良さそうな記事見つけたので貼っておきます！仕事終わったら読んでみます
https://uxdesign.cc/defining-colors-in-your-design-system-828148e6210a

**Comment by kazuhe** [comment]
Issue ありがとうございます！

> 僕的にはFigmaでカラーコードをきちんと定義しておいて、命名はFigmaとフロントで合わせておけば、コーディングするときはFigmaから名前を簡単に見れるので特に問題にならず楽にコーディングできるかなと思いました！

同意です！Figmaの方で定義しておいていただけるならコーディングする時は楽ですね！

**Comment by show-coco** [comment]
ありがとうございます！じゃあフロントエンドはその方針で行きますか
ただ、Figma上の命名は考える必要がありそうなので、少し調べてみます

@H37kouya こうやさんはどう思いますか？

**Comment by kazuhe** [comment]
そうですね。その方針でいきましょう！

命名難しいですね...
ちなみに、僕は有名どころのサービスのcss変数を参考にしていたりします。

<img width="1280" alt="Screen Shot 2021-06-26 at 17 06 58" src="https://user-images.githubusercontent.com/57878514/123506789-ff397880-d6a0-11eb-9142-469e1d8a058a.png">

**Comment by show-coco** [comment]
なるほど、Stripeは用途ベースで色分けてるみたいですね🤔
確かにこれだと、予期しない変更が起きなさそうですね
例えば、placeholderに使ってる色を変更したかったのに、他のところも変更されてるみたいなことが起きなさそう

**Comment by kazuhe** [comment]
> 例えば、placeholderに使ってる色を変更したかったのに、他のところも変更されてるみたいなことが起きなさそう

そうですね！ただ、毎度新しい用途が発生した場合新しいカラーを定義する必要が出てきますよね😂

`primary`などで色を定義しておくと定義の手間は減りますが影響範囲は大きくなるので予期しない変更がありそうですし...
トレードオフですよね。大規模になるまでは一旦、後者（用途毎ではなくアプリケーション内で使われる色（primary等）を予め定義しておく）でも良いのかも🤔（悩）

**Comment by H37kouya** [comment]
Figmaで定義した命名をアプリケーションでも使うでいいと思います！

> アプリケーション内で使われる色（primary等）を予め定義しておく

賛成！

用途ごとはちょっとだるくなりそう。個人的には、SpreadSheetに定義しておいて、それをFigma, アプリケーションで参照。

そして、SpreadSheetに以下のカラムを追加して、影響範囲を見積りやすくしたいなーと思いました。
「変数名」「カラーコード」「主な用途」

**Comment by kazuhe** [comment]
> SpreadSheetに定義しておいて、それをFigma, アプリケーションで参照。

> そして、SpreadSheetに以下のカラムを追加して、影響範囲を見積りやすくしたいなーと思いました。
「変数名」「カラーコード」「主な用途」

ありがとうございます！いいですね！
たしかにスプレッドシートの方が見やすいとは思うんですが、参照する対象が増えると頭がバグりそうなのでNotionでも良いかもですね！

**Comment by H37kouya** [comment]
表 = スプレッドシートのイメージになってました 🙄 
Notionで良さそうです！！

**Comment by show-coco** [comment]
おけです！じゃあ最初は用途ごとはコストが見合わないと言うことで、primary, secondaryなどである程度大まかに定義してみます
他のタスクはそのまま進めておいてもらって、以下の作業が終わり次第フロントも整えていきましょう
- カラーパレットをNotionかなんかにまとめる
- Figmaでもカラーパレットを使って着色する

[タスク](https://app.asana.com/0/1200430446735865/1200522765363893/f)
