### ISSUE TITLE
GraphQL vs. REST

### ISSUE THREAD

**Issue by show-coco** [show-coco/cloud-town#15]
議論のきっかけ↓
[なぜGraphQLを使うべきではないのか](https://itnews.org/news_contents/why_not_use_graphql)

**Comment by kazuhe** [comment]
ザッと記事を読みましたがどちらもメリット/デメリットあって悩みますね🤔

GraphQLの経験がなく判断が難しいのですが、一点気になったので質問（あんまり本質的じゃないかもですが）

GraphQLの場合フロントエンドはAPIの使用法をどの様に把握するんでしょう？実装見ていく感じになりますよね？（そんなに難しくはないか..）

RESTでOpen APIとかだとドキュメントとしては優秀な印象がありフロントからは把握しやすいのかな？と思いました。メンバーが流動的に変わる可能性もあるし。

_あと、超個人的な意見になりますがRESTでBFFアーキテクチャを勉強したいのでREST推しです。_

**Comment by show-coco** [comment]
実はApolloはドキュメントを自動生成してくれて、QueryやMutationもこのplaygroundで実行できて簡単に確かめられます！
サーバ起動して`localhost:4000/graphql`でこのplaygroundが開けます

![image](https://user-images.githubusercontent.com/53442928/123590376-844d9a80-d825-11eb-90a6-c69c295f58ec.png)

**Comment by kazuhe** [comment]
> QueryやMutationもこのplaygroundで実行できて簡単に確かめられます！

なんと！便利ですね。ありがとうございます！

> REST APIは、内部API、パートナーAPI、サーバー間のコミュニケーションに最適なツールだと思います。これはGraphQLがあまり得意としない分野です。RPCと並んで、この分野では大きな将来性があると思います。一方、GraphQLはリソースベースのAPIやRPCベースのAPIをラップしてくれます。

上記記事の抜粋ですが、Cloud townはどのパターンに該当するんでしょうかね。

間違ってたら教えていただきたいんですが、記事を見て受けた印象としてはRESTはいろいろと手間かかるけど拡張性と自由度（良い意味でも悪い意味でも）はGraphQLより勝っているのかなと思いました。

開発体験を優先するならGraphQL
今後の拡張性とかを優先するならREST
のような選択になるんでしょうか... （どちらもサーバー側をやったことないのであくまで推測）

**Comment by show-coco** [comment]
> 上記記事の抜粋ですが、Cloud townはどのパターンに該当するんでしょうかね。

今のところ内部APIに該当すると思います！将来的にチャットだけ負荷が高かったりして、マイクロサービスに分解するとしたら、チャットAPIはリソースAPIに当たるのかな？
その時にGraphQLでラップするっていう選択肢が出てくると、クライアントはRESTからGraphQLクライアントに大幅に移行しないといけないのでかなり移行コストが高くなりますね

今のところの比較ポイントはとりあえず以下の項目で決めちゃって良いのかなって思いますがどう思いますか？
- パフォーマンス（主にキャッシュ）
- Webクライアントでの開発コスト
  -> 開発体験や状態管理などで決まりそう
- 複数クライアントでの実装のコスト
  -> RESTの場合、BFFをそれぞれのクライアントに作ることになるがGraphQLの場合は1つで良い？
  -> GraphQL

**Comment by show-coco** [comment]
## パフォーマンス（主にキャッシュ）
- GraphQL: 
  - Pros: Apolloを使えば簡単に実現できる
  - Cons: Apollo Clientが使える言語を使用する必要がある。JavaScript, Swift, Kotlin, Javaなど
  - Cons: 複雑なクエリでのパフォーマンスの問題（N+1問題）
- REST:
  - Pros: Etagsを使用すればどのクライアントでもキャッシュを実装できる

## 開発コスト
開発体験や状態管理などで決まりそう
- GraphQL:
  - Pros: ドキュメントの自動生成
  - Pros: クライアントの型をサーバから自動生成（めっちゃ良い）
  - Cons: キャッシュの更新が複雑
- REST:
  - Pros: SWRを使えばキャッシュの更新が簡単
  - Cons: クライアントの型生成は[json-scheme](https://github.com/bcherny/json-schema-to-typescript#readme)を使用すれば可能だが管理が面倒。バックエンドもフロントもTSなのでクライアント-サーバ間のDTOを定義して共通利用すれば問題なさそう？

## 複数クライアントでの実装のコスト
- REST:
  - Cons: BFFをそれぞれのクライアントに作る必要がある
- GraphQL:
  - Pros: 各クライアント同じエンドポイントを使える

**Comment by show-coco** [comment]
複数クライアントでの実装が必要で、各クライアントBFFの実装コストを無くすためGraphQLを採用
